### ISSUE TITLE
No support for cookies in websocket header

### ISSUE THREAD

**Issue by millejoh** [ahyatt/emacs-websocket#38]
This trips up EIN when trying to connect to password-protected notebooks in IPython. emacs-websocket also needs to specify the port along with the URL in the header for the connection to be succesful in IPython.

I've coded up a crude solution (87ab400272ce2ab2127d1bb7b1176f19741a2eb8) over at my fork.

**Comment by ahyatt** [comment]
Thanks, let me look into this.

**Comment by ahyatt** [comment]
Looking at this more, I think the only reasonable way to support cookies is to tightly integrate with url-cookie.  If we support sending cookies, we probably should support handling set-cookie as well.  That means the client needs to call `url-cookie-store` before the call to `websocket-open`.  I'll proceed with this kind of implementation unless you have some specific objection.

**Comment by ahyatt** [comment]
Also, about the port issue - your code implies that the port is needed even if the port is unspecified (in other words, port 80).  If true, it seems like a violation of the RFC, which says:

   4.   The request MUST contain a |Host| header field whose value
        contains /host/ plus optionally ":" followed by /port/ (when not
        using the default port).

**Comment by ahyatt** [comment]
I've written a fix for the port issue to commit b7a1907b8c5cf9f8c0e680ceeb0b86e47a9965b9.  I've followed the RFC, though - so no port if it is the default.

**Comment by millejoh** [comment]
Tested b7a1907b8c5cf9f8c0e680ceeb0b86e47a9965b9 with ein and looks okay to me. EIN was working fine prior to this change, but I discovered not specifying the port in the request header was causing issues when dealing with secured IPython notebook servers. The problem is that without the port Tornado looks in the wrong place for the cookie. Not the most sterling technical explanation, I know, but I hope it makes some sense.

Also, I agree with the approach of calling `url-cookie-store`. Thanks for the help!

**Comment by ahyatt** [comment]
Please take a look at 542c6fec7447119c681d2a87da90a40223a81a36 and tell me if it works for you.  All tests pass, but I don't have an real server to test against with actual cookies.

**Comment by millejoh** [comment]
Works for me. Thanks very much for implementing this!

**Comment by ahyatt** [comment]
Both changes are now merged into the master branch, and I'll wait a few weeks to see if anyone reports any problems, and release a new version thereafter.

If you'd like me to release before that to fix the user problem, that's fine.
