### ISSUE TITLE
Add support for emacs 25

### ISSUE THREAD

**Issue by jgkamat** [ahyatt/emacs-websocket#46]
As Emacs 25 is released, people upgrading to packages that depend on web-socket will be expecting this to work (hopefully). Currently the websocket tests fail on emacs 25.

```
Debugger entered--Lisp error: (file-error "make client process failed" "Connection refused" :name "websocket to ws://127.0.0.1:9999" :buffer nil :host "127.0.0.1" :service 9999 :nowait nil)
  make-network-process(:name "websocket to ws://127.0.0.1:9999" :buffer nil :host "127.0.0.1" :service 9999 :nowait nil)
  websocket-open("ws://127.0.0.1:9999" :on-message (lambda (_websocket frame) (setq wstest-msgs (cons (websocket-frame-text frame) wstest-msgs)) (message "ws frame: %S" (websocket-frame-text frame)) (error "Test error (expected)")) :on-close (lambda (_websocket) (setq wstest-closed t)))
  (defvar wstest-ws (websocket-open "ws://127.0.0.1:9999" :on-message (function (lambda (_websocket frame) (setq wstest-msgs (cons (websocket-frame-text frame) wstest-msgs)) (message "ws frame: %S" (websocket-frame-text frame)) (error "Test error (expected)"))) :on-close (function (lambda (_websocket) (setq wstest-closed t)))))
  eval-buffer()  ; Reading at buffer position 2028
  funcall-interactively(eval-buffer)
```

Let me know if you cannot reproduce this, I tested with an empty config.

**Comment by ahyatt** [comment]
I've seen this occasionally myself on Emacs 25.  I'm not sure why yet, but it doesn't happen consistently, so I usually re-run and it works.  Can you try several times and see if it is consistently reproducible on your end?

**Comment by jgkamat** [comment]
Actually I just re-read the readme at the top of the tests, and I was just missing the tornado web server. I was trying to debug an issue in `emacs-slack` which uses this library (and dosen't work on emacs25), but your tests are passing for me in 24 and 25. I think I'll open an issue on the emacs-slack page now, since the tests here are passing fine. I guess this can be closed...
