### ISSUE TITLE
Add release tags

### ISSUE THREAD

**Issue by marcecj** [ahyatt/emacs-websocket#49]
It would be nice for this repository to have its releases tagged (at least version 1.7), so that packages can be generated for melpa-stable (see https://github.com/melpa/melpa/issues/2824).  Right now only the latest git master is packaged.

**Comment by ahyatt** [comment]
I definitely can do that.  I assume you mean just normal git tag with the
version number?  That is something I've done, but not consistently.

**Comment by marcecj** [comment]
Yeah, regular git tags should suffice :) .

**Comment by ahyatt** [comment]
I've tagged the last two releases (I made a new release while I was at it).  If you would like tags going back farther, that's fine, just let me know.
