### ISSUE TITLE
Custom headers in handshake

### ISSUE THREAD

**Issue by felipeochoa** [ahyatt/emacs-websocket#51]
I'm developing an [interactive websocket client](https://github.com/felipeochoa/websocket-client) to use for testing different APIs, but one of them requires the HTTP request to have a custom header. It would be great if there were a dynamic variable `websocket-extra-headers` that `websocket-create-headers` used to insert extra headers on the initial request.

**Comment by ahyatt** [comment]
I made a custom-headers branch with the changes you requested.  Let me know if that works for you, and if so, I'll merge it into the main branch and make a new release.

**Comment by felipeochoa** [comment]
Thanks! There's one small issue which I noted in the commit message, with that fixed, it works great!

**Comment by ahyatt** [comment]
Thanks for catching that!  I fixed this and checked it in, merged it to the main branch and incremented the version number.

**Comment by felipeochoa** [comment]
Great, thanks!
