### ISSUE TITLE
How to handle an error occured in `websocket-outer-filter`?

### ISSUE THREAD

**Issue by cireu** [ahyatt/emacs-websocket#54]
When websocket connection is invalid. `websocket-outer-filter` will force close the connection and signal an error. What should I do if I want to handle that error? (For example, I want to try to reconnect when an error occured)

My solution is create a new filter for the process but I think it's dirty hack

**Comment by ahyatt** [comment]
You can check for errors with `condition-case`.  If the websocket cannot connect, re-opening with `websocket-open` seems like the safest thing to do.

**Comment by cireu** [comment]
Can you try this piece of code?

```sh
aria2c --enable-rpc --rpc-listen-port=6800
```

```elisp
(condition-case _ (setq ws (websocket-open "ws://localhost:6800/unreachable)) (message "Error!"))
```

The `condition-case` won't work because you can connect to the server but you will get 404 response because `unreachable` doesn't exist, You will get

```
error in process filter: condition-case: Error response received from websocket server
error in process filter: Error response received from websocket server
```

The error was raised by `websocket-outer-filter` at https://github.com/ahyatt/emacs-websocket/blob/master/websocket.el#L789 asynchronously.

IMO, it shuold be possible to handle these errors by using callback, force throwing errors is not so user-friendly.

**Comment by ahyatt** [comment]
I see - yeah that's a problem.  After some investigation, I have a potential fix in the new `error-fix` branch: 0591322dc9e311f73270279a51b0bbf8b47d4f9c. With this, you should be able to handle an error in whatever you set to on-error.  I'm not sure this fix is complete good - it probably should throw if on-error is not set. I'll have to think about that case...

**Comment by cireu** [comment]
Thanks you, this works for me.

It seems that default error-handler is `websocket-default-error-handler`, why not just throw the error in that function?

**Comment by ahyatt** [comment]
Cool, this has been merged into the master branch, along with some other error issues I noticed.

**Comment by cireu** [comment]
thx for your work
