### ISSUE TITLE
Setting case-fold-search to nil results "Incorrect handhake from websocket" error

### ISSUE THREAD

**Issue by millejoh** [ahyatt/emacs-websocket#61]
Documented in issue [#600](https://github.com/millejoh/emacs-ipython-notebook/issues/600) over at ein. Apparently the accept header check in `websocket-verify-headers` needs to be case-insensitive along with the upgrade header check.

I cannot figure why a case-sensitive search would break this check, so I am a little concerned this is a Tornado/Jupyter specific issue in which case it would be better for me to work around the issue inside of ein (somehow).

**Comment by ahyatt** [comment]
This is news to me.  I checked the spec again, and it doesn't mention anything about this, in fact the value of Sec-Websocket-Accept is base64, which is case-sensitive.

However, you are correct that the upgrade should be case-insensitive.  I'll fix that.

**Comment by ahyatt** [comment]
Actually, looking at the code again, the check is already case-insensitive (it is wrapped in a `(let ((case-fold-search t)) ...)` block.  Being non-nil, searches and matches should ignore case.

**Comment by ahyatt** [comment]
Got it.  Thanks for the explanation.  That I can fix.

**Comment by ahyatt** [comment]
My fix is committed at 5be01c6d1a8e87d001916fc40a77d779826fcacf, can you try it out?

**Comment by millejoh** [comment]
Works for me - thank you!

**Comment by ahyatt** [comment]
Cool, I merged this into master and will follow up with a version update.  I usually push out to the gnu elpa a few weeks after github just to make sure there's no issues.
