### ISSUE TITLE
declares GPL-3+, but provided full-text license is GPL-2+

### ISSUE THREAD

**Issue by sten0** [ahyatt/emacs-websocket#62]
Hi,

I'm in the process of evaluating Atomic Chrome for Emacs for inclusion into the Debian archive.  Emacs Websocket is a dependency of it.  While reviewing the latter I noticed that all lisp files declare GPL-3+, but the provided full-text of the GPL is still 2+.  For your convenience, here is a link to GPL-3+:

https://www.gnu.org/licenses/gpl-3.0.txt

**Comment by ahyatt** [comment]
Fixed with 74e4b82bf1a2e9197875ebcc20c494b506095235.  The actual GPL version is 2, so I moved the version mentioned in the GPL files back to 2, instead of 3.  Thank you for catching this discrepancy.

**Comment by sten0** [comment]
Hi Andrew,

Andrew Hyatt <notifications@github.com> writes:

> Fixed with 74e4b82bf1a2e9197875ebcc20c494b506095235.  The actual GPL
> version is 2, so I moved the version mentioned in the GPL files back
> to 2, instead of 3.  Thank you for catching this discrepancy.

You're welcome, and thank you for the quick fix :-)  BTW since you write
"in the GPL files" I have to ask if any of the files are not GPL-2+.  I
had been supposing that `testserver.py` was under the same license.

Thanks,
Nicholas

**Comment by ahyatt** [comment]
Everything is under the same license.
