### ISSUE TITLE
Push to ELPA?

### ISSUE THREAD

**Issue by mplscorwin** [ahyatt/emacs-websocket#77]
If I'm understanding correctly, ELPA could perhaps catch up to 11-2020 per MELPA.   Also, I was thinking of using this to create something using obs-websocket.  I'll make a PR for the brag-list if my creation comes to life :)

**Comment by ahyatt** [comment]
I tend to wait a few months before pushing from MELPA to ELPA, just because I want some time to elapse before I make a release.  When I make a release I push to ELPA as well.  That should happen fairly soon.

What is `obs-websocket`?

**Comment by mplscorwin** [comment]
> I tend to wait a few months before pushing from MELPA to ELPA, just because I want some time to elapse before I make a release. When I make a release I push to ELPA as well. That should happen fairly soon.

Sounds like a good plan to me.  I created this ticket because it looked like the GNU ELPA and MELPA released versions were about 1yr different, but maybe I misunderstood.

> 
> What is obs-websocket?

[obs-websocket](https://github.com/Palakis/obs-websocket) is a plugin for Open Broadcaster Studio (OBS) that allows external programs and APIs to "control" OBS.  There are [quite a few github projects](https://github.com/topics/obs-websocket) using it.

Thanks for the reply (and for this great feature)!

**Comment by ahyatt** [comment]
FYI, I've pushed to ELPA yesterday.  Thanks for noting that it's been a while.
